# This type stub file was generated by pyright.

# 第三方无类型包（PyExecJS）__main__ 的最小存根；参数类型由 argparse 推断为
# 动态类型，故放宽本文件相关严格检查。
# pyright: reportGeneralTypeIssues=none, reportMissingParameterType=none, reportUnknownParameterType=none, reportImplicitOverride=none

from argparse import Action

class PrintRuntimes(Action):
    def __init__(self, option_strings, dest=..., default=..., help=...) -> None: ...
    def __call__(self, parser, namespace, values, option_string=...): ...

def main() -> None: ...

if "__main__" == __name__:
    ...
