# This type stub file was generated by pyright.

from abc import ABCMeta, abstractmethod

import six

@six.add_metaclass(ABCMeta)
class AbstractRuntimeContext:
    # Abstract base class for runtime context class.
    def exec_(self, source):
        # Execute source by JavaScript runtime and return all output to stdout as a string.
        #
        # source -- JavaScript code to execute.
        ...

    def eval(self, source):
        # Evaluate source in JavaScript runtime.
        #
        # source -- JavaScript code to evaluate.
        ...

    def call(self, name, *args):
        # Call a JavaScript function in context.
        #
        # name -- Name of funtion object to call
        # args -- Arguments for the funtion object
        ...

    @abstractmethod
    def is_available(self): ...
