# This type stub file was generated by pyright.

# 第三方无类型包（PyExecJS）的最小存根；方法参数由 six/argparse 推断为动态类型，
# 且以 @six.add_metaclass(ABCMeta) 声明抽象类（非继承 ABC），故放宽本文件相关严格检查。
# pyright: reportGeneralTypeIssues=none, reportMissingParameterType=none, reportUnknownParameterType=none

import six
from abc import ABCMeta, abstractmethod

@six.add_metaclass(ABCMeta)
class AbstractRuntime:
    # Abstract base class for runtime class.
    def exec_(self, source, cwd=...):
        # Execute source by JavaScript runtime and return all output to stdout as a string.
        #
        # source -- JavaScript code to execute.
        # cwd -- Directory where call JavaScript runtime. It may be ignored in some derived class.
        ...
    
    def eval(self, source, cwd=...):
        # Evaluate source in JavaScript runtime.
        #
        # source -- JavaScript code to evaluate.
        # cwd -- Directory where call JavaScript runtime. It may be ignored in some derived class.
        ...
    
    def compile(self, source, cwd=...):
        # Bulk source as a context object. The source can be used to execute another code.
        #
        # source -- JavaScript code to bulk.
        # cwd -- Directory where call JavaScript runtime. It may be ignored in some derived class.
        ...
    
    @abstractmethod
    def is_available(self):
        ...
    


