"""
This type stub file was generated by pyright.
"""

# 第三方无类型包（PyExecJS）的最小存根；异常类构造参数由运行时推断为动态类型，
# 故放宽本文件相关严格检查（与同包其他 execjs 存根一致）。
# pyright: reportAny=none, reportExplicitAny=none, reportMissingParameterType=none, reportUnknownParameterType=none

class Error(Exception):
    ...


class RuntimeError(Error):
    ...


class RuntimeUnavailableError(RuntimeError):
    ...


class ProcessExitedWithNonZeroStatus(RuntimeError):
    def __init__(self, status, stdout, stderr) -> None:
        ...
    


class ProgramError(Error):
    ...


