# This type stub file was generated by pyright.

from typing import Any

from execjs._abstract_runtime import AbstractRuntime
from execjs._abstract_runtime_context import AbstractRuntimeContext

class ExternalRuntime(AbstractRuntime):
    # Runtime to execute codes with external command.
    def __init__(self, name, command, runner_source, encoding=..., tempfile=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def name(self) -> Any:
        ...
    
    def is_available(self) -> bool:
        ...
    
    class Context(AbstractRuntimeContext):
        def __init__(self, runtime, source=..., cwd=..., tempfile=...) -> None:
            ...
        
        def is_available(self):
            ...
        
    
    


def node() -> ExternalRuntime:
    ...

def node_node() -> ExternalRuntime:
    ...

def node_nodejs() -> ExternalRuntime:
    ...

def jsc() -> ExternalRuntime:
    ...

def spidermonkey() -> ExternalRuntime:
    ...

def jscript() -> ExternalRuntime:
    ...

def phantomjs() -> ExternalRuntime:
    ...

def slimerjs() -> ExternalRuntime:
    ...

def nashorn() -> ExternalRuntime:
    ...

