# This type stub file was generated by pyright.

def encode_unicode_codepoints(s: str) -> str:
    # >>> encode_unicode_codepoints("a") == 'a'
    # True
    # >>> ascii = ''.join(chr(i) for i in range(0x80))
    # >>> encode_unicode_codepoints(ascii) == ascii
    # True
    # >>> encode_unicode_codepoints('\u4e16\u754c') == '\\u4e16\\u754c'
    # True
    ...

