"""
This type stub file was generated by pyright.
"""

from execjs._abstract_runtime import AbstractRuntime
from execjs._abstract_runtime_context import AbstractRuntimeContext

class PyV8Runtime(AbstractRuntime):
    '''Runtime to execute codes with PyV8.'''
    def __init__(self) -> None:
        ...
    
    @property
    def name(self) -> Literal['PyV8']:
        ...
    
    def is_available(self) -> bool:
        ...
    
    class Context(AbstractRuntimeContext):
        def __init__(self, source=...) -> None:
            ...
        
        def is_available(self) -> bool:
            ...
        
        @classmethod
        def convert(cls, obj) -> str | list[Any] | dict[Any, Any] | None:
            ...
        
    
    


