# This type stub file was generated by pyright.

from collections import OrderedDict
from typing import Any

def register(name, runtime) -> None:
    # Register a JavaScript runtime.
    ...

def get(name=...):
    # Return a appropriate JavaScript runtime.
    # If name is specified, return the runtime.
    ...

def runtimes() -> OrderedDict[Any, Any]:
    # return a dictionary of all supported JavaScript runtimes.
    ...

def get_from_environment() -> None:
    # Return the JavaScript runtime that is specified in EXECJS_RUNTIME environment variable.
    # If EXECJS_RUNTIME environment variable is empty or invalid, return None.
    ...

_runtimes = ...
