"""
最小类型存根：customtkinter 官方未发布类型信息，本项目为静态检查补一份最小声明。
仅覆盖 gui.py 实际用到的 API。

CTk* 控件在运行时继承自对应 tkinter 控件，故这里直接继承 tkinter 类以复用 typeshed
自带的方法。但 tkinter 的部分方法（pack/grid/configure…）存在返回非 None（如 _GridIndexInfo
或 config dict）的重载，导致调用结果未使用时触发 reportUnusedCallResult。为消除此类告警，
这里用 _CTkWidget 混入类在 MRO 中优先覆盖这些「副作用型」方法，统一返回 None；仅保留
get/index/create_*/winfo_children 等确实需要返回值的少数方法签名。
"""
import tkinter
from typing import Any


class _CTkWidget:
    # 副作用型方法：统一返回 None，消除 reportUnusedCallResult / reportUnknownMemberType
    def pack(self, *args: Any, **kwargs: Any) -> None: ...
    def grid(self, *args: Any, **kwargs: Any) -> None: ...
    def place(self, *args: Any, **kwargs: Any) -> None: ...
    def configure(self, *args: Any, **kwargs: Any) -> None: ...
    def config(self, *args: Any, **kwargs: Any) -> None: ...
    def lift(self, *args: Any, **kwargs: Any) -> None: ...
    def tkraise(self, *args: Any, **kwargs: Any) -> None: ...
    def after(self, *args: Any, **kwargs: Any) -> None: ...
    def after_cancel(self, *args: Any, **kwargs: Any) -> None: ...
    def bind(self, *args: Any, **kwargs: Any) -> None: ...
    def bind_all(self, *args: Any, **kwargs: Any) -> None: ...
    def unbind(self, *args: Any, **kwargs: Any) -> None: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def update_idletasks(self, *args: Any, **kwargs: Any) -> None: ...
    def yview(self, *args: Any, **kwargs: Any) -> None: ...
    def xview(self, *args: Any, **kwargs: Any) -> None: ...
    def see(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, *args: Any, **kwargs: Any) -> None: ...
    def insert(self, *args: Any, **kwargs: Any) -> None: ...
    def clipboard_append(self, *args: Any, **kwargs: Any) -> None: ...
    def clipboard_clear(self, *args: Any, **kwargs: Any) -> None: ...
    def clipboard_get(self, *args: Any, **kwargs: Any) -> None: ...
    def focus(self, *args: Any, **kwargs: Any) -> None: ...
    def focus_set(self, *args: Any, **kwargs: Any) -> None: ...
    def focus_force(self, *args: Any, **kwargs: Any) -> None: ...
    def withdraw(self, *args: Any, **kwargs: Any) -> None: ...
    def deiconify(self, *args: Any, **kwargs: Any) -> None: ...
    def iconify(self, *args: Any, **kwargs: Any) -> None: ...
    def title(self, *args: Any, **kwargs: Any) -> None: ...
    def geometry(self, *args: Any, **kwargs: Any) -> None: ...
    def resizable(self, *args: Any, **kwargs: Any) -> None: ...
    def minsize(self, *args: Any, **kwargs: Any) -> None: ...
    def maxsize(self, args: Any, **kwargs: Any) -> None: ...
    def protocol(self, *args: Any, **kwargs: Any) -> None: ...
    def grab_set(self, *args: Any, **kwargs: Any) -> None: ...
    def grab_release(self, *args: Any, **kwargs: Any) -> None: ...
    def wait_window(self, *args: Any, **kwargs: Any) -> None: ...
    def wait_visibility(self, *args: Any, **kwargs: Any) -> None: ...
    def transient(self, *args: Any, **kwargs: Any) -> None: ...
    def mainloop(self, *args: Any, **kwargs: Any) -> None: ...
    def quit(self, *args: Any, **kwargs: Any) -> None: ...
    def bell(self, *args: Any, **kwargs: Any) -> None: ...
    def iconbitmap(self, *args: Any, **kwargs: Any) -> None: ...
    def pack_propagate(self, *args: Any, **kwargs: Any) -> None: ...
    def grid_propagate(self, *args: Any, **kwargs: Any) -> None: ...
    def grid_columnconfigure(self, *args: Any, **kwargs: Any) -> None: ...
    def grid_rowconfigure(self, *args: Any, **kwargs: Any) -> None: ...
    def columnconfigure(self, *args: Any, **kwargs: Any) -> None: ...
    def rowconfigure(self, *args: Any, **kwargs: Any) -> None: ...
    def destroy(self, *args: Any, **kwargs: Any) -> None: ...
    def tag_config(self, *args: Any, **kwargs: Any) -> None: ...
    def tag_configure(self, *args: Any, **kwargs: Any) -> None: ...
    def tag_add(self, *args: Any, **kwargs: Any) -> None: ...
    def tag_remove(self, *args: Any, **kwargs: Any) -> None: ...
    def tag_bind(self, *args: Any, **kwargs: Any) -> None: ...
    def coords(self, *args: Any, **kwargs: Any) -> None: ...
    def itemconfig(self, *args: Any, **kwargs: Any) -> None: ...
    def itemconfigure(self, *args: Any, **kwargs: Any) -> None: ...
    def winfo_exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def winfo_ismapped(self, *args: Any, **kwargs: Any) -> bool: ...
    def winfo_x(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_y(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_width(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_height(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_rootx(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_rooty(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_pointerx(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_pointery(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_screenwidth(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_screenheight(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_reqwidth(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_reqheight(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_vrootx(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_vrooty(self, *args: Any, **kwargs: Any) -> int: ...
    def winfo_children(self, *args: Any, **kwargs: Any) -> list[tkinter.Widget]: ...
    def cget(self, *args: Any, **kwargs: Any) -> Any: ...
    def keys(self, *args: Any, **kwargs: Any) -> list[str]: ...
    def get(self, *args: Any, **kwargs: Any) -> str: ...
    def index(self, *args: Any, **kwargs: Any) -> str: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def state(self, *args: Any, **kwargs: Any) -> Any: ...
    def select(self, *args: Any, **kwargs: Any) -> None: ...
    def deselect(self, *args: Any, **kwargs: Any) -> None: ...
    def create_oval(self, *args: Any, **kwargs: Any) -> int: ...
    def create_rectangle(self, *args: Any, **kwargs: Any) -> int: ...
    def create_line(self, *args: Any, **kwargs: Any) -> int: ...


class CTk(_CTkWidget, tkinter.Tk):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkToplevel(_CTkWidget, tkinter.Toplevel):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkFrame(_CTkWidget, tkinter.Frame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkLabel(_CTkWidget, tkinter.Label):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkButton(_CTkWidget, tkinter.Button):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkTextbox(_CTkWidget, tkinter.Text):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkScrollbar(_CTkWidget, tkinter.Scrollbar):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkScrollableFrame(_CTkWidget, tkinter.Frame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkOptionMenu(_CTkWidget, tkinter.Frame):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set(self, value: str) -> None: ...
    def get(self) -> str: ...


class CTkFont:
    def __init__(
        self,
        family: str = ...,
        size: int = ...,
        weight: str = ...,
        slant: str = ...,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...


def set_appearance_mode(mode: str) -> None: ...
def get_appearance_mode() -> str: ...
def set_default_color_theme(theme: str) -> None: ...
