name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-repo-name:latest .
        docker push your-dockerhub-username/your-repo-name:latest
        
#推送到 Docker Hub： 使用 docker push 将构建的 Docker 镜像推送到 Docker Hub。确保将 your-dockerhub-username/your-repo-name 替换为你在 Docker Hub 上的仓库信息。
#在 GitHub 仓库的设置中，你还需要添加两个密钥，分别是 DOCKERHUB_USERNAME 和 DOCKERHUB_PASSWORD，用于存储你的 Docker Hub 用户名和密码。
