name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Aliyun Container Registry
      run: echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login --username "${{ secrets.ALIYUN_USERNAME }}" --password-stdin registry.cn-beijing.aliyuncs.com

    - name: Build and push Docker image
      run: |
        docker build -t registry.cn-beijing.aliyuncs.com/luoan-0517/douyin-live-recorder:latest .
        docker push registry.cn-beijing.aliyuncs.com/luoan-0517/douyin-live-recorder:latest
